version: "3"

volumes:
    weight-mg-php-fpm-socket:
    weight-mg-db-volume:
    weight-mg-test-db-volume:

services:
    weight-mg-app:
        container_name: weight-mg-app
        build: ./php
        volumes:
            - ../src/backend:/var/www
            - weight-mg-php-fpm-socket:/var/run/php-fpm
        depends_on:
            - weight-mg-db

    weight-mg-web:
        container_name: weight-mg-web
        build: ./nginx
        ports:
            - "8000:80"
        volumes:
            - ../src/backend:/var/www
            - weight-mg-php-fpm-socket:/var/run/php-fpm
        depends_on:
            - weight-mg-app

    weight-mg-db:
        container_name: weight-mg-db
        build: ./mysql
        ports:
            - "3306:3306"
        volumes:
            - weight-mg-db-volume:/var/lib/mysql
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: weight_mg

    weight-mg-test-db:
        container_name: weight-mg-test-db
        build: ./mysql
        ports:
            - "3307:3306"
        volumes:
            - weight-mg-test-db-volume:/var/lib/mysql
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: weight_mg_test
